### ISSUE TITLE
Low stability and false positives

### ISSUE THREAD

**Issue by terrancex** [zhunki/Superion#2]
I am experiencing low stability (<50%),  solely false positives (none of the crashes reproduce), and weirdly it says a whole cycle was finished in a short time, all while fuzzing jsc (release build).

Any clue to why?

Also, did you run it against the release or debug version of jsc? With or without asan?

**Comment by zhunki** [comment]
the number of new paths generated is extremely low, which is weird. I build jsc into the release version and use its original test cases as seeds. I build it without asan since it uses too much memory.

**Comment by terrancex** [comment]
Any clue to why it is happening on my setup?

Also, the afl-fuzz processes quit over time, within 12 hours, about 75% of them are gone. Super weird.. Still investigating

**Comment by zhunki** [comment]
since your jsc crashes on false positives, it should be a problem of how you build jsc.

**Comment by terrancex** [comment]
I build jsc just like in the readme
```
export CC=~/path_to_Superion/afl-clang-fast
export CXX=~/path_to_Superion/afl-clang-fast++
export AFL_HARDEN=1
./Tools/Scripts/build-jsc --jsc-only --j14
```

More importantly, I see there is a memory leak that causes the afl-fuzz processes to quit or halt after consuming 100% of the system's RAM.
