### ISSUE TITLE
Cannot build Superion

### ISSUE THREAD

**Issue by roxaaams** [zhunki/Superion#4]
Hello all,

I could not get the tool to build, even though I closely followed the build instructions and used the same tool versions, compiler versions  and OS as it was described in the documentation.

I got the following error: 

`Step 21/24 : RUN cd Superion/llvm_mode && LLVM_CONFIG=llvm-config-3.8 CXXFLAGS="-DLLVM38" make
 ---> Running in 6cd7db6eb15d
[*] Checking for working 'llvm-config'...
[*] Checking for working '/root/Superion/afl-gcc'...
[*] Checking for '../afl-showmap'...
[+] All set and ready to build.
/root/Superion/afl-gcc -O3 -funroll-loops -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -DAFL_PATH=\"/usr/local/lib/afl\" -DBIN_PATH=\"/usr/local/bin\" -DVERSION=\"2.52b\"  afl-clang-fast.c -o ../afl-clang-fast 
ln -sf afl-clang-fast ../afl-clang-fast++
/root/Superion/afl-g++ `llvm-config-3.8 --cxxflags` -fno-rtti -fpic -DLLVM38 -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -DVERSION=\"2.52b\" -Wno-variadic-macros -shared afl-llvm-pass.so.cc -o ../afl-llvm-pass.so `llvm-config-3.8 --ldflags` 
cc1plus: warning: command line option '-Wno-pointer-sign' is valid for C/ObjC but not for C++
afl-llvm-pass.so.cc: In member function 'virtual bool {anonymous}::AFLCoverage::runOnModule(llvm::Module&)':
afl-llvm-pass.so.cc:180:28: warning: variable 'instLine' set but not used [-Wunused-but-set-variable]
               unsigned int instLine = cDILoc->getLine();
                            ^
/root/Superion/afl-gcc -O3 -funroll-loops -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -DAFL_PATH=\"/usr/local/lib/afl\" -DBIN_PATH=\"/usr/local/bin\" -DVERSION=\"2.52b\"  -fPIC -c afl-llvm-rt.o.c -o ../afl-llvm-rt.o
afl-llvm-rt.o.c:249:1: warning: constructor priorities from 0 to 100 are reserved for the implementation
 __attribute__((constructor(CONST_PRIO))) void __afl_auto_init(void) {
 ^
/tmp/.afl-56-1563905864.s: Assembler messages:
/tmp/.afl-56-1563905864.s:5041: Error: symbol `__afl_area_ptr' is already defined
/tmp/.afl-56-1563905864.s:5042: Error: symbol `__afl_prev_loc' is already defined
Makefile:86: recipe for target '../afl-llvm-rt.o' failed
make: *** [../afl-llvm-rt.o] Error 1
The command '/bin/sh -c cd Superion/llvm_mode && LLVM_CONFIG=llvm-config-3.8 CXXFLAGS="-DLLVM38" make' returned a non-zero code: 2`

Everything is written in a Dockerfile which can be seen below. In order to build the docker I used the following command: docker build . --network=host

# Prepare OS and dependencies
FROM ubuntu:16.04
WORKDIR /root/
COPY antlr-4.7.2-complete.jar ./
RUN apt-get update && apt-get install -y curl git cmake xz-utils
RUN curl http://releases.llvm.org/3.8.0/clang+llvm-3.8.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz | tar xJf -
RUN apt-get update && apt-get install -y --no-install-recommends build-essential python3
RUN apt-get update && apt-get install -y --no-install-recommends apt-utils
RUN apt-get update && apt-get install -y --no-install-recommends wget software-properties-common
RUN apt-get update && apt-get install -y --no-install-recommends git
RUN apt-get install -y make cmake g++ pkg-config uuid-dev
RUN apt-add-repository "deb http://us.archive.ubuntu.com/ubuntu/ xenial universe" && apt-add-repository "deb http://us.archive.ubuntu.com/ubuntu/ xenial main restricted"
RUN apt-get update && apt-get install -y clang-3.8 libomp-dev libllvm3.8
# Cloning Superion  
RUN git clone https://github.com/zhunki/Superion
# Build ANTLR runtime 
RUN cd Superion/tree_mutation/ && cmake . && make -j2
# Build tree mutator for JS and PHP
RUN cd Superion/tree_mutation/php_parser && for f in *.cpp; do g++ -I ../runtime/src/ -c $f -fPIC -std=c++11; done && g++ -shared -std=c++11 *.o ../dist/libantlr4-runtime.a  -o libTreeMutation.so
RUN cd Superion/tree_mutation/js_parser && for f in *.cpp; do g++ -I ../runtime/src/ -c $f -fPIC -std=c++11; done && g++ -shared -std=c++11 *.o ../dist/libantlr4-runtime.a  -o libTreeMutation.so
# Build AFL
RUN cd Superion && make
ENV AFL_HARDEN=1
ENV CC=/root/Superion/afl-gcc
ENV CXX=/root/Superion/afl-g++
RUN cd Superion/llvm_mode && LLVM_CONFIG=llvm-config-3.8 CXXFLAGS="-DLLVM38" make
# Cloning and building JerryScript
RUN git clone https://github.com/jerryscript-project/jerryscript.git
RUN cd jerryscript/tools && python build.py --clean --debug --compile-flag=-fsanitize=address --compile-flag=-m32 --compile-flag=-fno-omit-frame-pointer --compile-flag=-fno-common --jerry-libc=off --static-link=off --lto=off --error-message=on --system-allocator=on
# Fuzzing JerryScript
RUN cd Superion && ./afl-fuzz -M f1 -m 1G -t 100+ -i ~/tree_mutation/js_parser/ -o ~/tree_mutation/js_parser/ ~/jerryscript/build/bin/jerry @@

**Comment by zhunki** [comment]
is your llvm version 3.8?

**Comment by zhunki** [comment]
why do you use afl to build afl?

in the following setting, you define the default compiler as afl-gcc/g++
````
ENV AFL_HARDEN=1
ENV CC=/root/Superion/afl-gcc
ENV CXX=/root/Superion/afl-g++
````
then you build afl-clang/clang++
````
RUN cd Superion/llvm_mode && LLVM_CONFIG=llvm-config-3.8 CXXFLAGS="-DLLVM38" make
````

**Comment by roxaaams** [comment]
I'd like to know whether this is the correct order:
1. Build the tree mutator
2. Build afl
3. Instrument the executable of the fuzzing target

Besides that, I'm interested about the llvm mode. Is it necessary?

**Comment by zhunki** [comment]
some target projects can't be compiled with gcc/g++, then you will need clang with llvm. otherwise, you don't need llvm-mode.

**Comment by roxaaams** [comment]
Alright.
What should I actually change in the dockerfile regarding the default compiler and the build of afl-clang/clang++? Also I am not sure what you mean by "use afl to build afl". Is there any other way to do it?

**Comment by thomas-vogel** [comment]
gcc/g++ should be the default ones and not afl-gcc/afl-g++. Thus, do _not_ set the env. variables 
```
ENV CC=/root/Superion/afl-gcc
ENV CXX=/root/Superion/afl-g++
```
before running `LLVM_CONFIG=llvm-config-3.8 CXXFLAGS="-DLLVM38" make`.

**Comment by roxaaams** [comment]
Ok. I deleted the env variables, but the build got blocked again with the following message:

Step 18/22 : ENV AFL_HARDEN=1
 ---> Using cache
 ---> 967a139de6d2
Step 19/22 : RUN cd Superion/llvm_mode && LLVM_CONFIG=llvm-config-3.8 CXXFLAGS="-DLLVM38" make
 ---> Running in f3d4569bc25f
[*] Checking for working 'llvm-config'...
[*] Checking for working 'clang'...
[-] Oops, can't find 'clang'. Make sure that it's in your $PATH (or set $CC and $CXX).
make: *** [test_deps] Error 1
Makefile:67: recipe for target 'test_deps' failed
The command '/bin/sh -c cd Superion/llvm_mode && LLVM_CONFIG=llvm-config-3.8 CXXFLAGS="-DLLVM38" make' returned a non-zero code: 2

**Comment by thomas-vogel** [comment]
Install clang: `apt install clang` (in addition to `clang-3.8`).

**Comment by roxaaams** [comment]
I installed clang alongside clang-3.8 and got this error:

Step 22/23 : RUN cd jerryscript/tools && python build.py --clean --debug --compile-flag=-fsanitize=address --compile-flag=-m32 --compile-flag=-fno-omit-frame-pointer --compile-flag=-fno-common --jerry-libc=off --static-link=off --lto=off --error-message=on --system-allocator=on
 ---> Running in bc27c743e71c
usage: build.py [-h] [--devhelp] [--builddir DIR] [--clean]
                [--cmake-param OPT] [--compile-flag OPT] [--debug]
                [--install [DIR]] [-j N] [--link-lib OPT] [--linker-flag OPT]
                [--lto X] [--shared-libs X] [--strip X] [--toolchain FILE]
                [-v] [--jerry-cmdline X] [--jerry-cmdline-snapshot X]
                [--jerry-ext X] [--jerry-libm X] [--jerry-port-default X]
                [--all-in-one X] [--cpointer-32bit X] [--error-messages X]
                [--external-context X] [--jerry-debugger X] [--js-parser X]
                [--line-info X] [--logging X] [--mem-heap SIZE]
                [--stack-limit SIZE] [--profile FILE] [--snapshot-exec X]
                [--snapshot-save X] [--system-allocator X] [--vm-exec-stop X]
build.py: error: unrecognized arguments: --jerry-libc=off --static-link=off

**Comment by thomas-vogel** [comment]
I got the same error, probably due to a newer version of Jerryscript that we are now using.
The build.py of Jerryscript does not know the two arguments: `--jerry-libc=off --static-link=off`.
Thus, I removed these two arguments from the call, but there could be alternative arguments (e.g., with different names) that achieve the same effect. Another option is to use the proper older version of Jerryscript.

**Comment by zhunki** [comment]
you are so patient, @thomas-vogel . Yes, you don't need to use the exact build options, you can change as your need. @roxaaams

**Comment by roxaaams** [comment]
I removed the two missing arguments as @thomas-vogel suggested and added the following dependencies: libc6 libc6-dev gcc-multilib g++-multilib. 
However, it looks like the JerryScript binary is not instrumented. There may be a problem with the latest version. @zhunki, do you remember which version of JerryScript you used?

This is the last error message: 

Step 26/26 : RUN cd Superion && AFL_SKIP_CPUFREQ=1 ./afl-fuzz -M f1 -m 1G -t 100+ -i ~/jerry_seeds/ -o ~/jerry_out/ ~/jerryscript/build/bin/jerry @@
 ---> Running in 812339fce432
afl-fuzz 2.52b by <lcamtuf@google.com>
[+] Looks like we're not running on a tty, so I'll be a bit less verbose.
[+] You have 8 CPU cores and 2 runnable tasks (utilization: 25%).
[+] Try parallel jobs - see docs/parallel_fuzzing.txt.
[*] Checking CPU core loadout...
[+] Found a free CPU core, binding to #0.
[*] Checking core_pattern...
[*] Setting up output directories...
[*] Scanning '/root/jerry_seeds/'...
[+] No auto-generated dictionary tokens to reuse.
[*] Creating hard links for all input files...
[*] Validating target binary...

[-] Looks like the target binary is not instrumented! The fuzzer depends on
    compile-time instrumentation to isolate interesting test cases while
    mutating the input data. For more information, and for tips on how to
    instrument binaries, please see docs/README.

    When source code is not available, you may be able to leverage QEMU
    mode support. Consult the README for tips on how to enable this.
    (It is also possible to use afl-fuzz as a traditional, "dumb" fuzzer.
    For that, you can use the -n option - but expect much worse results.)

[-] PROGRAM ABORT : No instrumentation detected
         Location : check_binary(), afl-fuzz.c:7028

The command '/bin/sh -c cd Superion && AFL_SKIP_CPUFREQ=1 ./afl-fuzz -M f1 -m 1G -t 100+ -i ~/jerry_seeds/ -o ~/jerry_out/ ~/jerryscript/build/bin/jerry @@' returned a non-zero code: 1

**Comment by zhunki** [comment]
which compiler did you use?

**Comment by roxaaams** [comment]
Clang 3.8 and llvm 3.8

**Comment by roxaaams** [comment]
@thomas-vogel, did you use the same versions of OS, compiler and tools? Also did you succeed in building and fuzzing with JerryScript?

**Comment by zhunki** [comment]
this time you should use afl-gcc/clang

**Comment by thomas-vogel** [comment]
That is, before building Jerryscript you should set the env variables:
```
export CC=~/path_to_Superion/afl-gcc
export CXX=~/path_to_Superion/afl-g++
```

**Comment by roxaaams** [comment]
I finally managed to fuzz JS by adding the following parameters to the build command of JerryScript: CC=/root/Superion/afl-gcc CXX=/root/Superion/afl-g++. 

Thanks for the help, @zhunki and @thomas-vogel!

**Comment by docfate111** [comment]
Could you include the new dockerfile please?
