### ISSUE TITLE
cc: error: ./tree_mutation/php_parser/libTreeMutation.so: No such file or directory

### ISSUE THREAD

**Issue by zhangysh1995** [zhunki/Superion#6]
Hi, I built for `js_parser` but why it asks for to build `php_parser`?

**Comment by zhunki** [comment]
Please change the MakeFile.

Yushan ZHANG <notifications@github.com> 于2019年12月20日周五 下午8:11写道：

**Comment by zhangysh1995** [comment]
I figured out that  I need to also build other parsers. Could you please update the `Readme`?

**Comment by zhunki** [comment]
just build the parser you need and change the makefile
